#!/bin/bash

# Copyright 2014 Yoshida Shin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

which pep8 >/dev/null
which py.test >/dev/null
which pyflakes >/dev/null
which doc8 >/dev/null

(
    cd $(git rev-parse --show-toplevel)
    pep8 --ignore E402 src
    find src -name '*.py' -a ! -name '__init__.py' | xargs pyflakes
    py.test src
    doc8 docs
    python setup.py check -r
)
